config/routes.rb
Omrails::Application.routes.draw do

  resources :trips

  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

  

end

app/models/trip.rb
class Trip < ActiveRecord::Base

	validates :description, presence: true

	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = current_user.trips.new
  end

  # GET /trips/1/edit
  def edit
    @trip = current_user.trips.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = current_user.trips.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    @trip = current_user.trips.find(params[:id])

    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = current_user.trips.find(params[:id])
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_footer.html.erb
<div class ="footer"> 
	<small>
		by Joe Amodio
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "One Month Rails", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	      	<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>	
			<ul class="nav pull-right">
        <% if user_signed_in? %>
           <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
	      	<li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
	      </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	
<body>

	<%= render 'layouts/header' %>
			<div class ="container">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
					<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is a project to teach
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %> in one month. This is the sample application. 

</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<h1>Welcome Back!</h1>
<% else %>
<div class="hero-unit">
<h1>Welcome to One Month Rails</h1>

<p>You've found the home page for the 
<%= link_to "One Month Rails", "http://onemonthrails.com"  %>
application.
</p>

<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-danger btn-large" %>
</p>
</div>
<% end %>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :description, as: :text, input_html: { rows: "3"} %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<tr>
    <td><%= trip.description %></td>
    <td><%= link_to 'Show', trip %></td>
    <% if current_user == trip.user %>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

<%= render @trips %>

  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			  <%= @trip.description %>
			</p>
			<p>
				<%= @trip.user.name %>
			</p>
			<% if current_user == @trip.user %>
			<%= link_to 'Edit', edit_trip_path(@trip) %> |
			<% end %>
			<%= link_to 'Back', trips_path %>
		</div>
	</div>
</div>